// Automatically generated by MockGen. DO NOT EDIT!
// Source: physics/physics.go

package physics

import (
	gomock "code.google.com/p/gomock/gomock"
	. "github.com/huin/chunkymonkey/types"
)

// Mock of IBlockQuerier interface
type MockIBlockQuerier struct {
	ctrl     *gomock.Controller
	recorder *_MockIBlockQuerierRecorder
}

// Recorder for MockIBlockQuerier (not exported)
type _MockIBlockQuerierRecorder struct {
	mock *MockIBlockQuerier
}

func NewMockIBlockQuerier(ctrl *gomock.Controller) *MockIBlockQuerier {
	mock := &MockIBlockQuerier{ctrl: ctrl}
	mock.recorder = &_MockIBlockQuerierRecorder{mock}
	return mock
}

func (_m *MockIBlockQuerier) EXPECT() *_MockIBlockQuerierRecorder {
	return _m.recorder
}

func (_m *MockIBlockQuerier) BlockQuery(blockLoc BlockXyz) (bool, bool) {
	ret := _m.ctrl.Call(_m, "BlockQuery", blockLoc)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

func (_mr *_MockIBlockQuerierRecorder) BlockQuery(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BlockQuery", arg0)
}
